
" Vundle configuration.
set nocompatible           " Never comment this out!
runtime vimrc_vundle       " Contains lines that may be commented out.
filetype plugin indent on  " Never comment this out!

runtime vimrc_syntastic
runtime vimrc_ycm

if   &term == "xterm"
\ || &term == "stterm-256color"
\ || &term == "screen"
\ || &term == "screen.xterm-256color"
   set t_Co=256
   colorscheme inkpot
endif

set   ai
set   backspace=1
set   bs=2
set   expandtab
set   history=100
set   incsearch
set   laststatus=2
set   mouse=a
set   mousefocus
set   mousehide
set norestorescreen
set   shiftwidth=3
set   showmatch
set   statusline=%-f\ %m\ %y\ row=%l\ col=%c
set   tabstop=8
set   textwidth=79
set nowrap

syntax on
set hlsearch

setlocal grepprg="pcregrep -n $* /dev/null"
command! -buffer -nargs=1 Cgrep grep <q-args> `find . -iname '*.c' -o -iname '*.cpp' -o -iname '*.h' -o -iname '*.hpp'`

highlight ExtraWhitespace ctermbg=green guibg=green
match ExtraWhitespace /\s\+$/

" This allows for packages locally installed (under ~/.vim/bundle) for pathogen
" to be used.
"execute pathogen#infect()

