#!/bin/bash

obconfdir=$1

# Line up dockapps in sequence.
dockapps=(\
  "bbpager -c ${obconfdir}/bbpager.rc -w"\
  "wmacpi"\
  "wmnd"\
  "wmmon -l -i"\
  "wmmon -l -s"\
  "wmmon -l"\
  "wmtop -U -r 2000"\
  "wmforkplop"\
  "wmhdplop"\
)
max_off=$((${#dockapps}-1))
for i in $(seq 0 $max_off); do
  ${dockapps[$i]} &
  sleep 1
done

